"""empty message

Revision ID: b2fc3e4b1069
Revises: c6ad39c8e7df
Create Date: 2022-06-11 13:58:56.102610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2fc3e4b1069'
down_revision = 'c6ad39c8e7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('contact', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('contact', 'work_ph',
               existing_type=sa.VARCHAR(length=17),
               nullable=True)
    op.create_unique_constraint(None, 'contact', ['mobile'])
    op.create_unique_constraint(None, 'contact', ['email'])
    op.create_foreign_key(None, 'contact', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_constraint(None, 'contact', type_='unique')
    op.drop_constraint(None, 'contact', type_='unique')
    op.alter_column('contact', 'work_ph',
               existing_type=sa.VARCHAR(length=17),
               nullable=False)
    op.alter_column('contact', 'last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('contact', 'user_id')
    # ### end Alembic commands ###
