"""empty message

Revision ID: c6ad39c8e7df
Revises: e7b36101ceab
Create Date: 2022-06-09 00:12:21.261328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ad39c8e7df'
down_revision = 'e7b36101ceab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('email', sa.String(length=50), nullable=False))
    op.alter_column('contact', 'work_ph',
               existing_type=sa.VARCHAR(length=17),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact', 'work_ph',
               existing_type=sa.VARCHAR(length=17),
               nullable=False)
    op.drop_column('contact', 'email')
    # ### end Alembic commands ###
